### ISSUE TITLE
Provide an option to update an rst page with expected output

### ISSUE THREAD

**Issue by astrofrog** [scientific-python/pytest-doctestplus#107]
When writing documentation, it would be nice to have a mode where pytest-doctestplus can actually generate the output for all the commands in an .rst file (unless this already exists and I missed it?)

**Comment by effigies** [comment]
FWIW I had the same desire, but in actual doctests. Numpy changed their default print options a while back, and now that I'm dropping support for 1.13, I wanted to move to the new approach automatically.

I created this patch: https://github.com/astropy/pytest-doctestplus/compare/master...effigies:enh/fixup_runner

I don't know if it also works on RST pages, since I think we manually updated ours (running `make doctest` didn't fail).

This is a fairly hacky beginning, but could probably be cleaned up to fit better into this module if people are interested.

**Comment by seberg** [comment]
Just to note, I have a decent start on this which probably should work for most things (numpy is tricky for various reasons w.r.t. to doctest not finding the correct files); it is going through the final steps for me to make a PR.

(I don't really expect this to be necessarily polished, i.e. it is something to run once in a while, so breaking changes should be expected to be OK, I think.)
